### ISSUE TITLE
Settings support

### ISSUE THREAD

**Issue by cybertschunk** [AnonymOnline/btw17#11]
Write support for settings files for VWahl.

**Comment by cybertschunk** [comment]
For documentation take a look at https://doc.qt.io/qt-5/qsettings.html

**Comment by HasseDosch** [comment]
Settings do now work fine, I want to apologize for my thoughtless commits with earlier settings-functions -.-

**Comment by cybertschunk** [comment]
I wouldn't recreate the settings object every time we need it. Maybe the plotting will have to store data laterwards as well or do you want to use different settings files? @HasseDosch

**Comment by HasseDosch** [comment]
First of all we have the option to use multiple settings files while recreating it. But I think we should not do it in such a way, because a QSettings file refers to a program and company name. Therefore we have the option to use setting-groups with settings.beginGroup("etc"). According to their [documentation](https://doc.qt.io/qt-5/qsettings.htmll) 

> Constructing and destroying a QSettings object is very fast 

. Nevertheless they do it in the same way in their basic examples of using QSettings. @AnonymOnline

**Comment by cybertschunk** [comment]
I've moved the settings object to the project namespace now anyway. @HasseDosch
