### ISSUE TITLE
please merge your branches more often

### ISSUE THREAD

**Issue by Anonym0nline** [AnonymOnline/btw17#64]
Like now ;)

Merge your branches as soon, as you implemented a feature. then delete the old branch and create a new branch, named after a new feature, you are going to implement. This helps to have an overview and prevents big merge conflicts.

for example, website is either a dead branch (then delete) or a branch, which waits to be merged into the main branch.

**Comment by cybertschunk** [comment]
All in all I agree with you, but we are still in a quite early development state. I guess actually it's easyśier to continue the work in different branches, moreover because many workers don't have much experience in the work with git. Once we have built a basic structure, we will work as you recommended.

**Comment by Anonym0nline** [comment]
alright then, under wich OS are you developing the visualisation?

**Comment by cybertschunk** [comment]
@Anonym0nline we are developing with linux.

**Comment by cybertschunk** [comment]
@Anonym0nline I've now merged the plotting branch into master and will develop, as you recommend. I guess, you can close this issue?

**Comment by HasseDosch** [comment]
I will close this issue now due to inactivity
